## Problem 2 - Data manipulation and selection (4 points)

In this problem you will clean the data from our data file by removing no-data values, convert temperature values in Fahrenheit to Celsius, and split the data into separate datasets using the weather station identification code. We will start this problem by cleaning and converting our temperature data. Please perform the tasks below by writing your code into the codeblocks in each section.

### Tips for completing this problem

- Use **exactly** the same variable names as in the instructions because the tests rely on following the same formatting or variable naming as in the instructions.
- **Please do not**:

    - **Change the file names**. Do all of your editing in the provided `Exercise-5-problem-2.ipynb` file (this file).
    - **Change the existing cell types**. You can add cells, but changing the cell types for existing cells (from code to markdown, for example) will also cause the automated grader to fail. 

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Creating a new dataframe called `selected` that contains select columns from the data file
- Cleaning the new dataframe by removing no-data values
- Creating a new column for temperatures converted from Fahrenheit to Celsius
- Dividing the data into separate dataframes for the Mactan (Cebu) and Hinatuan (Surigao del Sur) stations
- Saving the new dataframes to CSV files
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem
- Uploading your notebook and data files to your GitHub repository for this week's exercise

### Part 1 (0 points)

The first step for this problem is to read the data file `ph_tempdata.csv` again into a variable `data` using pandas. Remember to specify the no-data values (you can copy your code from Problem 1).

In [44]:
# Creating the data frame

import pandas as pd

data = pd.read_csv("ph_tempdata.csv", na_values= ["*", "**", "***", "****", "*****", "******"])

Check that the first rows of the DataFrame look ok:

In [4]:
print(data.head(1))

       STATION                           NAME  LATITUDE  LONGITUDE  ELEVATION  \
0  RPM00098646  MACTAN CEBU INTERNATIONAL, RP    10.308    123.979        9.4

         DATE  TEMP   MAX  MIN
0  2017-01-01  79.7  86.0  NaN

Check the number of rows in the DataFrame:

In [5]:
data_length= len(data)
print(data_length)

2921

### Part 2 (1 point)

Next, your task is to subset the data and remove rows with missing temperature values.

- Select the columns `STATION`, `DATE`, `TEMP`, `MAX`, and `MIN` from the `data` dataframe and assign them to the variable `selected`
- Remove all rows from `selected` that have NoData in the column `TEMP` using the `dropna()` function

In [45]:
# Creating new data frame called selected and removing no datas

selected = data[["STATION", "DATE", "TEMP", "MAX", "MIN"]].dropna()

Check that you selected the correct column names:

In [10]:
selected.head()

       STATION        DATE   TEMP    MAX    MIN
2  RPM00098646  2017-01-03  82.40  88.52  76.64
4  RPM00098646  2017-01-05  81.32  88.52  77.00
6  RPM00098646  2017-01-07  79.88  84.56  76.10
7  RPM00098646  2017-01-08  77.90  79.16  76.28
8  RPM00098646  2017-01-09  78.98  83.30  75.92

Check how many rows you have after removing the no-data values:

In [11]:
len(selected)

1704

### Part 3 (1 point)

Next, you can convert the temperature values in Fahrenheit to Celsius.

- Create a new column in `selected` called `Celsius`
- Convert the Fahrenheit temperatures from `TEMP` using the conversion formula below and store the results in the new `Celsius` column.

$$
\Large
\begin{equation}
  T_{\mathrm{Celsius}} = (T_{\mathrm{Fahrenheit}} - 32)~/~1.8
\end{equation}
$$

- Round the values in the `Celsius` column to have 0 decimals (**do not** create a new column, update the current one)
- Convert the `Celsius` values into integers (**do not** create a new column, update the current one)

In [32]:
# Adding new column called CELSIUS and converting values from temp column

selected["CELSIUS"] = (selected["TEMP"] - 32)/1.8

In [33]:
# Check your dataframe
selected.head()

       STATION        DATE   TEMP    MAX    MIN  CELSIUS
2  RPM00098646  2017-01-03  82.40  88.52  76.64     28.0
4  RPM00098646  2017-01-05  81.32  88.52  77.00     27.4
6  RPM00098646  2017-01-07  79.88  84.56  76.10     26.6
7  RPM00098646  2017-01-08  77.90  79.16  76.28     25.5
8  RPM00098646  2017-01-09  78.98  83.30  75.92     26.1

In [34]:
# Check data types
print(selected.dtypes)

STATION     object
DATE        object
TEMP       float64
MAX        float64
MIN        float64
CELSIUS    float64
dtype: object

### Part 4 (1 point)

Your next task is to divide `selected` into two separate dataframes. Please use the given variable names and write your answer to the codeblock below.

- Select all rows from the `selected` DataFrame with the `STATION` code `RPM00098646` into a variable called `mactan`
- Select all rows from the `selected` DataFrame with the `STATION` code `RP000098755` into a variable called `hinatuan`

In [37]:
# Dividing the selected data frame into two

mactan = selected[selected["STATION"]== "RPM00098646"]
hinatuan = selected[selected["STATION"] == "RP000098755"]

In [38]:
# Check the dataframe
print(f"Mactan: \n{mactan.head()}\n")

Mactan:
       STATION        DATE   TEMP    MAX    MIN  CELSIUS
2  RPM00098646  2017-01-03  82.40  88.52  76.64     28.0
4  RPM00098646  2017-01-05  81.32  88.52  77.00     27.4
6  RPM00098646  2017-01-07  79.88  84.56  76.10     26.6
7  RPM00098646  2017-01-08  77.90  79.16  76.28     25.5
8  RPM00098646  2017-01-09  78.98  83.30  75.92     26.1

In [39]:
# Check the dataframe
print(f"Hinatuan: \n{hinatuan.head()}\n")

Hinatuan:
          STATION        DATE   TEMP    MAX    MIN  CELSIUS
1461  RP000098755  2017-01-01  80.06  84.20  75.20     26.7
1462  RP000098755  2017-01-02  80.78  85.64  75.92     27.1
1464  RP000098755  2017-01-04  80.60  86.36  75.38     27.0
1468  RP000098755  2017-01-08  77.18  81.86  73.40     25.1
1469  RP000098755  2017-01-09  80.60  85.64  74.12     27.0

### Part 5 (1 point)

Now you can save your selections to csv files.

- Save the `mactan` DataFrame into the file `Mactan_temps_2019-01_2020-12.csv` (CSV format) 
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Save the `hinatuan` DataFrame into the file `Hinatuan_temps_2019-01_2020-12.csv` (CSV format) 
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Remember to commit both data files to your Exercise 5 repository

In [43]:
# Savings new data frames to csv with two-decimal place parameter

mactan.to_csv("Mactan_temps_2019-01_2020-12.csv", float_format="%.2f")
hinatuan.to_csv("Hinatuan_temps_2019-01_2020-12.csv", float_format ="%.2f")

In [42]:
#Read-only cell for hidden tests :)

### Problem 2 summary

- Was anything unclear to you in Problem 2?
- Did you encounter any problems with decimal formatting?

Also, make sure you:

- Check that your code includes informative comments explaining what your code does
- Commit and push your changes to your GitHub repository for Exercise 5 (including your 2 new data files)

Please write your answers and comments below (**activate the cell by double clicking**).

None

### On to Problem 3

Now you can continue to [Problem 3: Data analysis](Exercise-5-problem-3.ipynb)